---
sudo_defaults:
  - defaults: env_reset
  - defaults: secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  - name: 'admin'
    defaults: '!requiretty'
sudo_users:
  - name: 'admin'
    nopasswd: yes

admin_user: admin     # default user to add authorized_key to
